# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Clustering Analysis of English Demographic Data
author: Ella Stubbings
logo: haringey-icon.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns:
    - "rough-work/*.ipynb"


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - smartquotes
    - substitution
    - linkify
    - tasklist
    - attrs_inline

bibtex_bibfiles:
  - references.bib

citation:
  style: harvard-cite-them-right.csl

    


# Information about where the book exists on the web
repository:
  url: https://github.com/estubbings/summer-bursary-project  # Online location of your book
  path_to_book: cluster-analysis  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: haringey-icon.jpeg # optional, for the browser tab icon
  logo: haringey-icon.jpeg
  navbar_title: 

